// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSGhF3X5NfSf4Y1491S0FMN9vZwg1piSI',
    appId: '1:385795818514:web:eb7ea2fb3ad31cbac684cb',
    messagingSenderId: '385795818514',
    projectId: 'brewsphere-cc67e',
    authDomain: 'brewsphere-cc67e.firebaseapp.com',
    storageBucket: 'brewsphere-cc67e.firebasestorage.app',
    measurementId: 'G-E65BZ1XDXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7KUqy61H64PS3WOhGLxlhuoZ7SZwPx8I',
    appId: '1:385795818514:android:a849ae4ee8af18cdc684cb',
    messagingSenderId: '385795818514',
    projectId: 'brewsphere-cc67e',
    storageBucket: 'brewsphere-cc67e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZiGnx_A1e1BTp_wTTrnFzEXb3avNCmkI',
    appId: '1:385795818514:ios:40fc6d1fea85c39dc684cb',
    messagingSenderId: '385795818514',
    projectId: 'brewsphere-cc67e',
    storageBucket: 'brewsphere-cc67e.firebasestorage.app',
    androidClientId: '385795818514-3h9g1pn39hl03nn9hp7nd6vebsc0hqf8.apps.googleusercontent.com',
    iosClientId: '385795818514-bslushv203o378uic9k6fplnc3a928os.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZiGnx_A1e1BTp_wTTrnFzEXb3avNCmkI',
    appId: '1:385795818514:ios:40fc6d1fea85c39dc684cb',
    messagingSenderId: '385795818514',
    projectId: 'brewsphere-cc67e',
    storageBucket: 'brewsphere-cc67e.firebasestorage.app',
    androidClientId: '385795818514-3h9g1pn39hl03nn9hp7nd6vebsc0hqf8.apps.googleusercontent.com',
    iosClientId: '385795818514-bslushv203o378uic9k6fplnc3a928os.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSGhF3X5NfSf4Y1491S0FMN9vZwg1piSI',
    appId: '1:385795818514:web:52b40d3b4c2d0550c684cb',
    messagingSenderId: '385795818514',
    projectId: 'brewsphere-cc67e',
    authDomain: 'brewsphere-cc67e.firebaseapp.com',
    storageBucket: 'brewsphere-cc67e.firebasestorage.app',
    measurementId: 'G-SJQDZ49J0Y',
  );

}